linters:
  enable:
    - gosimple
  presets:
    - bugs
    - complexity
    - error
    - import
    - metalinter
    - module
    - performance
    - unused
linters-settings:
  # TIP: to fix linter complaints for any linter that supports auto-fixing, run:
  #       golangci-lint run --fix
  funlen:
    lines: 100
  cyclop:
    max-complexity: 10
  errcheck:
    check-type-assertions: true
    check-blank: true
    disable-default-exclusions: true
  revive:
    rules:
      # Force the linter to detect unhandled errors from every package, including fmt
      - name: unhandled-error
        arguments: []
  wrapcheck:
    # Ignore wrapping errors that are internal to the application
    ignorePackageGlobs:
      - github.com/TheFriendlyCoder/rejigger/*
run:
  #tests: false
  skip-files:
    # Ignore files that are partially vendored
    - lib/thirdparty/aferoWrapper.go