linters:
  enable:
    # default
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    # custom
    - cyclop
    - goerr113
  presets:
    - bugs
#    - complexity
    - error
#    - format
#    - import
#    - metalinter
    - module
    - performance
#    - sql
#    - style
#    - test
#    - unused
linters-settings:
  cyclop:
    max-complexity: 10
  errcheck:
    check-type-assertions: true
    check-blank: true
    disable-default-exclusions: true
run:
  #tests: false
  skip-files:
    # Ignore files that are partially vendored
    - lib/aferoWrapper.go