baseURL = 'https://thefriendlycoder.github.io/rejigger/'
languageCode = 'en-us'
title = 'Rejigger templating tool'

# For search functionality
[outputs]
home = [ "HTML", "RSS", "SEARCH"]

[params]
# This controls whether submenus will be expanded (true), or collapsed (false) in the
# menu; if no setting is given, the first menu level is set to false, all others to true;
# this can be overridden in the pages frontmatter
alwaysopen = true
# Prefix URL to edit current page. Will display an "Edit" button on top right hand corner of every page.
# Useful to give opportunity to people to create merge request for your doc.
# See the config.toml file from this documentation site to have an example.
editURL = "https://github.com/TheFriendlyCoder/rejigger/tree/main/docs/content/"
# Author of the site, will be used in meta information
author = "thefriendlycoder@gmail.com"

[module]
[[module.imports]]
path = 'github.com/McShelby/hugo-theme-relearn'